[build]
target = "x86_64.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
[unstable]
build-std-features = ["compiler-builtins-mem"]
# recompile the list to our arch
build-std = ["core", "compiler_builtins"]
